require("chris.options")
require("chris.keymaps")
require("chris.plugins")
require("chris.colorscheme")
require("chris.cmp")
require("chris.lsp")
-- require("chris.tresitter")
require("chris.toggleterm")
require("chris.telescope")
require("chris.nvim-tree")
require("chris.bufferline")
require("chris.whichkey")
